let arrayProductos = [
  {codigo: 1,  nombre: `Anteojo de descanso`, precio: 5000, stock: 20, imagen: `imagenes/accesorios/anteojos1.webp`},
  {codigo: 2, nombre: `Anteojo fashion`, precio: 4500, stock: 15, imagen: `imagenes/accesorios/anteojos2.webp`},
  {codigo: 3, nombre: `Anteojo de sol tornasolado`, precio: 10000, stock: 30, imagen: `imagenes/accesorios/anteojos3.webp`},
  {codigo: 4, nombre: `Anillo plata con diamante`, precio: 20000, stock: 40, imagen: `imagenes/accesorios/anillo1.jpg`},
  {codigo: 5, nombre: `Anillo de fantasía`, precio: 1000, stock: 80, imagen: `imagenes/accesorios/anillo2.webp`},
  {codigo: 6, nombre: `Anillo de oro 18k`, precio: 2500, stock: 20, imagen: `imagenes/accesorios/anillo3.webp`},
  {codigo: 7, nombre: `Pantalones estampados`, precio: 5000, stock: 20, imagen: `imagenes/pantalones/pantalon1.jpg`},
  {codigo: 8, nombre: `Pantalon negro chupin`, precio: 7500, stock: 40, imagen: `imagenes/pantalones/pantalon2.jfif`},
  {codigo: 9, nombre: `Pantalones de jean`, precio: 5500, stock: 60, imagen: `imagenes/pantalones/pantalon3.jpg`},
  {codigo: 10, nombre: `Pantalones rosado`, precio: 6500, stock: 30, imagen: `imagenes/pantalones/pantalon4.jpeg`},
  {codigo: 11, nombre: `Remeras para estampar`, precio: 3000, stock: 100, imagen: `imagenes/remeras/remera1.jpg`},
  {codigo: 12, nombre: `Remeras estampadas`, precio: 4500, stock: 20, imagen: `imagenes/remeras/remera2.jfif`},
  {codigo: 13, nombre: `Remeras de niños`, precio: 3500, stock: 40, imagen: `imagenes/remeras/remera3.jpeg`},
  {codigo: 14, nombre: `Remera marca Fila`, precio: 8000, stock: 20, imagen: `imagenes/remeras/remera4.webp`},
  {codigo: 15, nombre: `Zapatilla orange`, precio: 15000, stock: 20, imagen: `imagenes/zapatillas/zapatillas1.jpg`},
  {codigo: 16, nombre: `Zapatillas blancas`, precio: 18000, stock: 20, imagen: `imagenes/zapatillas/zapatillas2.webp`},
  {codigo: 17, nombre: `Zapatillas multicolor`, precio: 20000, stock: 10, imagen: `imagenes/zapatillas/zapatillas3.jpg`},
  {codigo: 18, nombre: `Zapatillas Nike rojas`, precio: 25000, stock: 10, imagen: `imagenes/zapatillas/zapatilla4.webp`},  
];

